# Generated by Django 4.2.9 on 2024-11-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='navigate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Изображение'),
        ),
    ]
